openapi: 3.0.1
info:
  title: Order API
  version: "1.0"
servers:
- url: http://localhost:8082
  description: Generated server url
paths:
  /api/orders:
    get:
      tags:
      - order-controller
      operationId: getAllOrders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
      - order-controller
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /api/orders/{oid}:
    delete:
      tags:
      - order-controller
      operationId: deleteOrder
      parameters:
      - name: oid
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
    patch:
      tags:
      - order-controller
      operationId: updateOrder
      parameters:
      - name: oid
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userId:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        userName:
          type: string
