spring:
  application.name: createOrderService
  jackson.serialization.indent_output: true

management:
  endpoints.web.exposure.include:
    - '*'
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true

resilience4j:
  circuitbreaker:
    instances:
      createOrderService:
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  ratelimiter:
    instances:
      createOrderService:
        limitForPeriod: 3
        limitRefreshPeriod: 5s
        timeoutDuration: 5s
        registerHealthIndicator: true
  retry:
    instances:
      createOrderService:
        maxRetryAttempts: 3
        waitDuration: 5s
        registerHealthIndicator: true